# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_author_book_publisher_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
    ]
