# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
